/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.buman.player;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-01-13")
public enum RoleEnum implements org.apache.thrift.TEnum {
  WARIOR(1),
  MAGE(2),
  WARLOCK(3),
  PRIEST(4),
  DRUID(5);

  private final int value;

  private RoleEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RoleEnum findByValue(int value) { 
    switch (value) {
      case 1:
        return WARIOR;
      case 2:
        return MAGE;
      case 3:
        return WARLOCK;
      case 4:
        return PRIEST;
      case 5:
        return DRUID;
      default:
        return null;
    }
  }
}
